name: glacier
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports.zstd=1.3.0
  - boto3=1.42.25
  - botocore=1.42.25
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cffi=2.0.0
  - click=8.3.1
  - colorama=0.4.6
  - cryptography=46.0.3
  - daiquiri=3.0.0
  - exceptiongroup=1.3.1
  - greenlet=3.3.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - iniconfig=2.3.0
  - jmespath=1.0.1
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=25.0
  - pip=25.3
  - pluggy=1.6.0
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-json-logger=2.0.7
  - python_abi=3.11
  - readline=8.3
  - s3transfer=0.16.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=1.4.46
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wheel=0.45.1
  - zstd=1.5.7
prefix: /home/servilla/miniconda3/envs/glacier
